# X-Trainer 配置文件模板
# 版本: 1.0 | 作者：Junhao Xiao | 项目地址：https://github.com/Codecode-X/X-Trainer

# ======================= 全局配置 (Global) =======================
VERBOSE: True  # 启用详细日志输出（如训练进度、指标等）
SEED: 42  # 全局随机种子，确保实验可复现性
USE_CUDA: True  # 自动检测并使用可用 GPU 加速计算
OUTPUT_DIR: "./output"  # 输出目录（存储日志/模型/评估结果）
RESUME: ""  # 断点续训路径（需包含`checkpoint.pth`文件）

# ===================== 训练引擎配置 (Engine) =====================
TRAINER:
  NAME: "TrainerClip"  # 训练器类名
  PREC: "amp"  # 训练精度：fp32、fp16、amp（自动混合精度）
  FROZEN_LAYERS: False  # 冻结基础网络层（仅训练分类头）

# 训练流程
TRAIN:
  DO_EVAL: True  # 每个 epoch 后验证模型（保存最佳模型）
  NO_TEST: False  # 训练完成后跳过测试阶段
  CHECKPOINT_FREQ: 5  # 模型保存频率（单位：epoch）
  PRINT_FREQ: 5  # 训练日志打印间隔（单位：batch）
  MAX_EPOCH: 20  # 最大训练轮次（单位：epoch）

# 测试流程
TEST:
  FINAL_MODEL: "best_val"  # 测试模型选择（best_val 或 last_step）
  SPLIT: "test"  # 测试数据集选择（val 或 test）

# ===================== 数据管理配置 (Data) ===================== 
# 数据集
DATASET:
  NAME: "Caltech101"  # 数据集类名
  DATASET_DIR: "/root/caltech-101"  # 数据集根目录
  SPLIT: [0.7, 0.1, 0.2]  # 训练/验证/测试集划分比例
  NUM_SHOTS: -1  # 每类样本数：-1=全量，0=零样本，≥1=小样本学习
  IMAGE_DIR: "/root/caltech-101/101_ObjectCategories"  # 图像目录 - 分类数据集基础配置

# 数据加载
DATALOADER:
  BATCH_SIZE: 32  # 训练批大小（影响显存占用）
  NUM_WORKERS: 4  # 数据加载并行进程数（建议=CPU 核心数）
  K_TRANSFORMS: 1  # 每种增强在原始图像上（横向）重复应用次数
  RETURN_IMG0: False  # 是否返回原始未增强图像（用于可视化或对比学习）

# 数据采样
SAMPLER:
  TRAIN_SP: "RandomSampler" # 训练集采样器类名（随机采样）
  TEST_SP: "SequentialSampler" # 测试集采样器类名（顺序采样）

# 图像增强
INPUT:
  # 输入图像尺寸，需与模型兼容
  SIZE: 224

  # 图像缩放插值方法，可选：bilinear, bicubic, nearest
  INTERPOLATION: "bilinear"

  # 在转换为张量之前的数据增强方法列表
  BEFORE_TOTENSOR_TRANSFORMS: ["TransformClipVisual"]

  # 在转换为张量之后的数据增强方法列表
  AFTER_TOTENSOR_TRANSFORMS: [""]

  # 特定模型增强策略
  TransformClipVisual: None  # CLIP 专用预处理 (无额外配置)

# ===================== 模型配置 (Model) =====================
MODEL:
  NAME: "Clip"  # 模型类名
  
  # 特定 Clip 模型配置
  pretrained: "ViT-B/16"  # 预训练模型名称（如 ViT-B/16）
  download_root: "~/.cache/clip"  # 预训练模型下载目录

# ===================== 学习率策略配置 (LR) =====================

# 学习率调度器
LR_SCHEDULER:
  NAME: "CosineLR" # 学习率调度器类名

  # 学习率预热器
  WARMUP:
    NAME: "LinearWarmupScheduler" # 预热器类名
    WARMUP_RECOUNT: True # 是否在预热结束后重置周期
    EPOCHS: 5 # 预热轮数
    MIN_LR: 1e-6  # 最小学习率


# ===================== 评估器配置 (evaluator) =====================
EVALUATOR:
  NAME: "EvaluatorClassification"  # 评估器类型，适用于分类任务
  per_class: True  # 是否评估每个类别的结果
  calc_cmat: True  # 是否计算混淆矩阵



# ===================== 优化器配置 (Optimizer) =====================
OPTIMIZER:
  NAME: "Adam"  # 优化器类名
  LR: 5e-4  # 学习率

  # 特定于 Adam 优化器的参数
  BETAS: [0.9, 0.999]  # Adam 优化器的 beta 参数
  WEIGHT_DECAY: 0.01  # 权重衰减（L2 正则化）
  EPS: 1e-8  # Adam 优化器的 epsilon 参数
  AMSGRAD: False  # 是否使用 AMSGrad 变体


# ===================== 使用说明 ========================
# 完整配置文档参考：https://github.com/Codecode-X/X-Trainer/wiki